#!/bin/sh

# Run tests for affected projects
npx nx affected --target=test

# Typecheck affected projects
npx nx affected --target=typecheck

# Build affected projects
npx nx affected --target=build

# Build affected projects
npm run test:all:standalone
