#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run tests for affected projects
npx nx affected --target=test

# Build affected projects
npx nx affected --target=build

# Typecheck affected projects
npx nx affected --target=typecheck
